general:
    root_dir:               '/home/neduchal/Data/data/sitmp/jackal/'
    data_dir:               'data'

gui:
    image_panel:
        width: 640
        height: 480
    map:
        width: 750
        height: 750
    layers:
        photo:              false
        navigation:         false

control:
    controller:
        steering_axes:      0
        throttle_axes:      3
        stop_button:        0
        gear_down_button:   6
        gear_down_button:   7

map_to_image:
    map_subscriber_topic:           '/map'
    pose_subscriber_topic:          '/pose_from_tf'
    tile_size_subscriber_topic:     '/map_tile_size'
    tile_size: 6

photographer:


